

class Episode {
    constructor(season, ep, title, summary) {
        this.season = season;
        this.ep = ep;
        this.title = title;
        this.summary = summary;
    }
}

var bigmouth = {
    1: new Episode(1, 1, "Ejaculation", "As Andrew falls under the spell of the aroused Hormone Monster, Nick becomes obsessed with the lack of changes in his own body."),
    2: new Episode(1, 2, "Everybody Bleeds", "A field trip goes from awkward to mortifying when Jessi gets her first period."),
    3: new Episode(1, 3, "Am I Gay?", "A trailer for a new movie starring The Rock leaves Andrew questioning his sexuality; Jessi and Nick's budding romance turns ugly."),
    4: new Episode(1, 4, "Sleepover: A Harrowing Ordeal of Emotional Brutality", "While the boys head to Jay's for a testosterone-fuelled sleepover, Jessi throws a party of her own."),
    5: new Episode(1, 5, "Girls Are Horny Too", "A steamy novel inspires Jessi to explore her own sexuality, and leaves the boys confused about what girls really want."),
    6: new Episode(1, 6, "Pillow Talk", "Nick brings Andrew into the city to visit an old camp crush, but the day doesn't go as planned; Jay embarks on an emotional journey with his pillow."),
    7: new Episode(1, 7, "Requiem for a Wet Dream", "Andrew struggles to keep the Hormone Monster in check as he works with Missy on a science fair project; Jessi and Matthew have fun at Jay's expense."),
    8: new Episode(1, 8, "The Head Push", "When Leah hosts a party for the high school drama crowd, Nick wrestles with a romantic dilemma; Andrew and Missy witness a disturbing scene."),
    9: new Episode(1, 9, "I Survived Jessi's Bat Mitzvah", "Family arguments, secret liaisons and an unflattering dress make Jessi's bat mitzvah a night to remember."),
    10: new Episode(1, 10, "The Pornscape", "While attempting to drown his sorrows, Andrew becomes hopelessly addicted to porn; Coach Steve becomes a suspect in a murder spree."),
    11: new Episode(2, 1, "Am I Normal?", "Andrew struggles to blend in after a growth spurt, Nick worries his hormones are out of whack, and Jessi and Jay get a taste of the teen runaway life."),
    12: new Episode(2, 2, "What Is It About Boobs?", "A classmate's booming bosom sends the boys into a rapture -- and leaves the girls with a raging case of insecurity; Coach Steve drops a bombshell."),
    13: new Episode(2, 3, "The Shame Wizard", "As Nick tries to figure out whether he has a shot with Gina, a mortifying encounter with Leah sends Andrew into a spiral of shame."),
    14: new Episode(2, 4, "Steve the Virgin", "Coach Steve finally gets his chance to do sex on a lady; Nick and Andrew go on a double date; Jessi's rebellious streak leads to big trouble."),
    15: new Episode(2, 5, "The Planned Parenthood Show", "An argument in sex ed class turns into a skit-tastic journey through the worlds of Planned Parenthood, contraceptives and STDs."),
    16: new Episode(2, 6, "Drug Buddies", "Jessi and Nick dip into her dad's stash of edibles, with mind-bending results; Andrew searches for the right moment to break up with Lola."),
    17: new Episode(2, 7, "Guy Town", "While helping Greg move into a seedy bachelor complex, the boys and their dads debate what women want -- and what it means to be a man."),
    18: new Episode(2, 8, "Dark Side of the Boob", "A school sleepover turns messy as Nick dishes on a makeout session and the Shame Wizard works his miserable magic on the whole class."),
    19: new Episode(2, 9, "Smooch or Share", "Nick tries to lighten the mood at the sleepover with a new twist on Truth or Dare; the Shame Wizard meets his match; Jessi vows to change her ways."),
    20: new Episode(2, 10, "The Department of Puberty", "After traveling through a magic portal to puberty headquarters, Nick seeks out a new Hormone Monster and Jessi bonds with the Depression Kitty."),
    21: new Episode(3, 1, "My Furry Valentine", "Sappy cards. Stupid clichés. And so much pressure. For Andrew, Nick, Jessi and friends, Valentine's Day is a total freaking minefield.")
};

var rickandmorty = {
    1: new Episode(1, 1, "Pilot", "Rick, in a drunken state, takes his grandson, Morty, for a ride in his flying car and rambles on about how he plans to use a neutrino bomb to wipe out all life on Earth. Rick lands the vehicle on Morty's demand and passes out. The bomb activates by itself and seems to be left unchecked, but ultimately it is shown that life on Earth remains intact. After having breakfast with their family, Rick takes Morty to another dimension to collect seeds of \"Mega Trees\", which Morty is forced to hide in his own rectum to get past intergalactic customs."),
    2: new Episode(1, 2, "Lawnmower Dog", "On Jerry's demand, Rick gives Snuffles, the family dog, an intelligence-enhancing helmet. Rick and Morty, in an Inception-esque scenario, enter the dream of Morty's teacher, in an attempt to make him give Morty an \"A\" in math class. They find themselves in a dangerous situation, where they are forced to repeatedly enter dreams within dreams to escape. Meanwhile, at home, Snuffles builds a mechanical suit and assembles a dog army intending to take over Earth."),
    3: new Episode(1, 3, "Anatomy Park", "On Christmas, Rick sends Morty inside the body of a homeless man to save his life (a parody of Fantastic Voyage). Inside the man's body is a microscopic enclosure called Anatomy Park (a parody of Jurassic Park), which houses various deadly diseases that escape their enclosures. Back at the family home, Jerry's parents visit, and the family attempts to bond without electronic devices."),
    4: new Episode(1, 4, "M. Night Shaym-Aliens!", "Aliens hold Rick and Jerry captive in a virtual reality, in an attempt to steal Rick's recipe for Concentrated Dark Matter. As Rick attempts escape, he discovers that there are multiple virtual reality layers on top of each other. Jerry, on the other hand, despite numerous system glitches, remains completely oblivious, and keeps trying to sell his advertising slogan for apples. Rick finally games the aliens by giving them a fake recipe. The aliens send Rick and Jerry on their way, and their ship explodes as they prepare the concoction."),
    5: new Episode(1, 5, "Meeseeks and Destroy", "After killing deadly enemies in an alternative dimension, Morty complains that Rick's adventures are too dangerous and traumatizing. This leads them into a \"Jack and the Beanstalk\" type adventure, where Morty is in charge. He decides to steal the giant's treasure and give it to the villagers. The giant dies by accident, Rick and Morty are charged with murder but are ultimately acquitted. Rick and Morty then descend from the Giants' beanstalk realm and stop in a fairy tale pub on the way down. There, King Jellybean attempts to rape Morty, but Morty escapes. Rick wins money playing poker and gives it to the villagers. As Rick and Morty are leaveing this dimension, Rick kills King Jellybean. Meanwhile, Beth, Summer and Jerry use Rick's \"Meeseeks Box\" to spawn Meeseeks, blue creatures that fulfill one request and then explode."),
    6: new Episode(1, 6, "Rick Potion #9", "Morty is interested in going to the dance at his school with his classmate Jessica, so he asks Rick for a love potion. However, because Jessica has the flu, the potion becomes airborne and goes haywire, causing not only her but the whole population of Earth to fall for Morty save for blood relatives. Rick attempts to fix up an antidote, but he fails twice, ultimately causing all humans affected by the love potion to turn into mutated monsters called \"Cronenbergs\""),
    7: new Episode(1, 7, "Raising Gazorpazorp", "In a pawn shop in space, Rick buys Morty a sex robot. Soon after, the robot conceives Morty's alien hybrid child whom he names Morty Jr. Rick and Summer go to the sex robot's planet of origin, Gazorpazorp, to find better suited parents for Morty Jr. After discovering that the Gazorpazorpian females are the dominant gender on the planet, Rick and Summer learn that the males of this species mature in only days and are, by nature, extremely violent. Morty Jr.'s quick aging teaches Morty about parenting."),
    8: new Episode(1, 8, "Rixty Minutes", "As the family watches The Bachelor, Rick is dissatisfied with the quality of Earth TV so he upgrades the cable to show programming from every conceivable dimension. Eventually, they see Jerry from an alternative reality on TV. The family, minus Rick and Morty, uses Rick's goggles to see through the eyes of their duplicates in that alternative reality, where Jerry and Beth have successful lives, they never married, and Summer was never born because Beth had an abortion. Jerry, Beth and Summer have a heated discussion in which they conclude that family life is holding them back and Beth admits that Summer was an unwanted pregnancy."),
    9: new Episode(1, 9, "Something Ricked This Way Comes", "Summer works in an antique shop run by the Devil, which gives away items that come with harmful curses. Rick sets up a competitor shop where he uses science to remove the curses, and the Devil is put out of business. Summer helps him to relaunch a successful dot-com company, but he betrays her and keeps the company for himself. Summer and Rick build muscle mass and publicly beat up the Devil to get revenge. Meanwhile, Jerry, helping Morty with his homework, insists that Pluto is a planet. They are abducted by Plutonians to their planet, where Jerry is mistaken for a scientist."),
    10: new Episode(1, 10, "Close Rick-counters of the Rick Kind", "The show's original Rick is wrongfully accused of murdering twenty-seven Ricks from alternate dimensions and kidnapping their respective Mortys. The Trans-Dimensional Council of Ricks arrests him and finds him guilty, upon discovering incriminating evidence which was actually fabricated to frame him. Rick and Morty escape and are chased by a few duplicates of themselves. The Smith household is flooded with other Ricks and Jerry develops a friendship with the good-natured \"Doofus Rick\". The real culprits seem to be an evil Rick and his Morty. They have been using Mortys' low intelligence brainwaves as a way to conceal themselves. They capture the original Rick and Morty, but the original Morty leads a rebellion of alternate Mortys and releases the original Rick. Rick informs the Council about the real killer, thus clearing his own name. After Rick and Morty depart, the Council discovers that Evil Rick was actually under control by an unknown puppet-master, which was Evil Morty all along. Evil Morty escapes by blending into the crowd of orphaned Morties."),
    11: new Episode(1, 11, "Ricksy Business", "Jerry and Beth participate in a reenactment of Titanic, but the ship unexpectedly fails to sink. Jerry spends some time alone with Lucy, a female janitor who eventually proves to be a deranged fan of the movie, forcing him to imitate scenes with her at gunpoint. She almost rapes Jerry, but Beth saves him. Meanwhile, Rick is left in charge of Morty and Summer, but they have a large party. Among the guests are teenagers, aliens, Gearhead, Squanchy, alternate Ricks and Abradolf Lincler (a DNA combination of Adolf Hitler and Abraham Lincoln). Rick, Morty and Summer only have minutes to spare before Beth and Jerry arrive, so they use a contraption to freeze time, allowing them to repair the house."),
    12: new Episode(2, 1, "A Rickle In Time", "Continuing from \"Ricksy Business\", Rick, Morty and Summer spend six months repairing the house and screwing around with time frozen. After unfreezing it, the trio ends up in a decaying dimension. They split into separate timelines whenever they are uncertain about something. Rick becomes paranoid, thinking that his duplicates want to kill him, but eventually he calms down. A creature in charge of safeguarding time appears and gives them collars that integrate all the timelines, then attempts to arrest them because Rick stole the time-freezing crystal."),
    13: new Episode(2, 2, "Mortynight Run", "Rick takes Morty on a trip to teach him how to pilot the flying car. When Rick realizes that Jerry has followed them without being noticed in the back seat, he leaves him in a daycare specifically designed for Jerries from alternate realities. Jerry socializes with other Jerries, some of them left there indefinitely because their Rick and Morty never returned. Rick sells an antimatter gun to Krombopulous Michael, an alien assassin who intends to use it to eliminate a gaseous being whom Rick nicknames Fart that is held captive by alien authorities."),
    14: new Episode(2, 3, "Auto Erotic Assimilation", "Rick attempts to loot a damaged spaceship with Morty and Summer. They find Unity, a hive mind and Rick's ex-lover. It plans to eventually assimilate the whole universe. Beta 7 is a male hive mind who has a crush on Unity, which it rejects. In a planet completely assimilated by Unity, it and Rick have parties, have sex, and drink and use drugs together. In light of all the revelry, it loses control and the planet is left messy and untended."),
    15: new Episode(2, 4, "Total Rickall", "Alien parasites plant fake memories in the minds of Rick, Morty, Beth, Jerry and Summer and pretend they are friends and family members. Every time the family reminisces about the past, the aliens reproduce. The family can't distinguish real people from aliens, so eventually they can't even trust each other. To prevent further spread, Rick locks down the house."),
    16: new Episode(2, 5, "Get Schwifty", "A massive alien head (a \"Cromulon\") appears over Earth, demanding to hear an original song, so Rick and Morty improvise \"Get Schwifty\". The whole planet is abducted and forced to participate in a musical talent show, where the losers' planets are obliterated via plasma ray. Morty steals Rick's portal gun and leaves him alone with Ice-T to make a hit original song and save earth."),
    17: new Episode(2, 6, "The Ricks Must Be Crazy", "Rick's flying car won't start, so he investigates the problem. The car's battery contains a miniature universe, from which Rick has been stealing electricity. Inside it, Zeep Xanflorp, that universe's top scientist, created a second miniature universe for the same purpose. Rick, Morty and Zeep are left stranded in a third miniature universe, as the pilot commits suicide and destroys his ship."),
    18: new Episode(2, 7, "Big Trouble in Little Sanchez", "Rick becomes \"Tiny Rick\" by transferring his mind to a teenager clone of himself in order to kill a vampire in Morty and Summer's school. Tiny Rick is outgoing and popular, but subconsciously cries for help in song lyrics and drawings. Meanwhile, Jerry and Beth experience couple therapy on an alien planet."),
    19: new Episode(2, 8, "Inter-dimensional Cable 2: Tempting Fate", "Jerry is treated in an alien hospital after unknowingly ingesting some bacteria stored by Rick, while his family is in the waiting room, watching an assortment of TV channels from alternate realities. Jerry is asked by doctors to donate his penis, to be converted into a replacement heart to save the life of civil rights activist Shrimply Pibbles. "),
    20: new Episode(2, 9, "Look Who's Purging Now", "Rick and Morty visit another planet and witness \"The Festival\", an annual event where the local populace commits crimes for one night without consequence. Rick compares it to The Purge movies. Morty forces Rick to rescue Arthricia, a young alien girl. She betrays them and steals Rick's gun and spaceship, leaving Rick and Morty to fend for themselves. "),
    21: new Episode(2, 10, "The Wedding Squanchers", "Rick and his family attend the wedding of Birdperson and Tammy, whose guest list includes seventeen of the Federation's most wanted — including Rick and Birdperson. At the wedding reception, Tammy reveals herself to be a Federation agent and kills Birdperson. Numerous agents invade the building, starting a battle against the guests."),
    22: new Episode(3, 1, "The Rickshank Rickdemption", "Rick is interrogated via a mind-computer link, inside a galactic federal prison. Summer and Morty attempt to rescue him but they are captured by SEAL Team Ricks, who take them to the Citadel of Ricks and decide to assassinate Rick. Back at the prison, Rick tricks both the federal agents and his aspiring assassins by switching bodies with them."),
    23: new Episode(3, 2, "Rickmancing the Stone", "Rick takes Morty and Summer to a post-apocalyptic version of Earth, where they are chased by a group of scavengers, known as Death Stalkers. Rick notices that the group is carrying a valuable rock of Isotope 322, so he and the kids join them in hope of stealing it. Summer falls in love with the Death Stalkers' leader."),
    24: new Episode(3, 3, "Pickle Rick", "Rick turns himself into a pickle to get out of attending a school-sanctioned family therapy, but Beth takes Rick's serum which would revert the transformation. Left alone, Rick eventually rolls into an open sewer drain, where he manages to manipulate the nervous systems of dead roaches and rats to build himself a mobile exoskeleton, with added weapons such as razors and drills."),
    25: new Episode(3, 4, "Vindicators 3: The Return of Worldender", "At Morty's insistence, Rick agrees to join the Vindicators, a group of intergalactic superheroes, to fight their archnemesis, Worldender. Rick cannot hide his disdain for the superheroes, while Morty is thrilled. The next morning, the Vindicators enter Worldender's base. They find that, while Rick was blackout drunk the previous night, he had killed Worldender and set up a variety of puzzles that the Vindicators must solve to survive. "),
    26: new Episode(3, 5, "The Whirly Dirly Conspiracy", "To bolster Jerry's self-esteem, Rick takes him on an adventure at Morty's request. They visit an otherworldly resort within an immortality field so Jerry won't be harmed while away. Jerry encounters Risotto Groupon, an alien who blames Rick for his kingdom being usurped. Risotto enlists Jerry in a plot to kill Rick, but Jerry backs out after Rick apologizes for ruining his marriage."),
    27: new Episode(3, 6, "Rest and Ricklaxation", "After a six-day outer space adventure that leaves them on the verge of psychological collapse, Rick and Morty decide to spend some time at an alien spa, where they use a machine that extracts a person's negative personality traits. However, without Rick and Morty knowing, those traits are transposed into toxic physical counterparts, characterized by Rick's arrogance and Morty's self-loathing."),
    28: new Episode(3, 7, "The Ricklantis Mixup", "As Rick and Morty adventure to Atlantis, the episode shifts focus towards the Citadel, a secret society populated by numerous versions of Ricks and Mortys. Despite being the underdog, the Morty Party candidate manages to secure the presidency. When his campaign manager receives information that the new president is in fact Evil Morty from the first-season episode \"Close Rick - counters of the Rick Kind\", he attempts to assassinate him but he fails. Evil Morty orders the execution of a shadow council of Ricks and anybody else he considers a potential threat to his rule."),
    29: new Episode(3, 8, "Morty's Mind Blowers", "After Morty requests to have a traumatic memory deleted, Rick reveals a room where he has been storing a number of memories he has removed from Morty's mind. However, as it turns out, besides the memories that Morty did not want to keep from their adventures, the room also contains memories in which Rick was made to look foolish, so he had them forcibly removed from Morty."),
    30: new Episode(3, 9, "The ABC's of Beth", "Rick and Beth enter Froopyland, a fantasy world created by Rick for young Beth. Their goal is to recover Tommy, Beth's childhood friend who has been trapped in Froopyland, and prevent the execution of his father, who is being falsely accused of eating him. Tommy, who has survived all these years by resorting to bestiality, incest and cannibalism, refuses to return to the real world."),
    31: new Episode(3, 10, "The Rickchurian Mortydate", "The President calls on Rick and Morty to defeat a monster in the tunnels underneath the White House, which they do with little effort. Annoyed that he constantly calls on them without any gratitude, they go back home, with the President quickly finding out. The resulting argument leads to a battle of egos that culminates in a fight in the White House between Rick and the President's security."),
}


var finalspace = {
    1: new Episode(1, 1, "Chapter One", "Gary, after five lonely years in a space prison, meets an alien he calls Mooncake, and vows to keep it safe. What Gary doesn't realize, however, is that Mooncake is also a planet destroyer."),
    2: new Episode(1, 2, "Chapter Two", "Gary and Avocato must stop a bounty hunter named Terk from telling the Lord Commander that Mooncake is on the Galaxy One; meanwhile the former prisoner has a disastrous first encounter with the Lord Commander."),
    3: new Episode(1, 3, "Chapter Three", "Gary and Avocato try to hide Mooncake safely away on the planet Yarno, but end up trapped in a terrifying mind-puzzle; Mooncake is forced to fight in a combat arena called the Deathcropolis; Quinn investigates the gravitational disturbance."),
    4: new Episode(1, 4, "Chapter Four", "After the Galaxy One is hacked, Gary has to harvest energy from a nearby star to reignite the engines and escape; the radiation poisoning from the star sends Gary into a trance of painful memories; Gary and Quinn are finally reunited."),
    5: new Episode(1, 5, "Chapter Five", "Gary, Quinn, and Avocato trace the cause of the gravitational disturbance to an eerie bioluminescent planet, and must put a stop to whatever is causing it."),
    6: new Episode(1, 6, "Chapter Six", "Gary and Avocato go on a mission to save Avocato's son, Little Cato, from the Lord Commander's prison planet."),
    7: new Episode(1, 7, "Chapter Seven", "Gary grapples with his future when he learns that his prison sentence is up."),
    8: new Episode(1, 8, "Chapter Eight", "Gary and his crew encounter a Titan named Bolo, who tells them how to close the breach in the fabric of space."),
    9: new Episode(1, 9, "Chapter Nine", "The crew of the Galaxy One returns to Earth to find an anti-matter bomb that they hope can save the universe."),
    10: new Episode(1, 10, "Chapter Ten", "Gary, Quinn and the team engage in a final confrontation with the Lord Commander to decide the fate of Earth and the universe."),
};

var blackmirror = {
    1: new Episode(1, 1, "The National Anthem", "Princess Susannah, a member of the British royal family, has been kidnapped. To return the Princess, the kidnapper demands that the country's Prime Minister, Michael Callow, has sexual intercourse with a pig on live television, otherwise he will kill her. Callow refuses to be blackmailed, but public opinion is gradually turning against him. "),
    2: new Episode(1, 2, "Fifteen Million Merits", "Bing feels trapped living in an enclosed, automated space, as a member of a society that rides power-generating stationary bikes in exchange for \"merits\", a form of currency they can use to buy things they need. One day, he hears a girl named Abi singing in the bathroom and falls in love with her. He decides to gift her fifteen million merits, that she can use to buy a ticket for a talent show."),
    3: new Episode(1, 3, "The Entire History of You", "People have implanted a \"grain\" behind their ear, which allows them to record everything they see and hear. Using a remote, a user can perform a \"re -do\", playing back their memories directly to their eye or to a video monitor. At a dinner party, Liam is suspicious of his wife Ffion's behaviour towards a man named Jonas."),
    4: new Episode(2, 1, "Be Right Back", "Ash lives with his girlfriend Martha, spending a lot of time on social media, until one day he dies in a traffic accident. A few days later, Martha finds out that she is pregnant and decides to use a new technology that is able to simulate Ash's voice and personality on the phone, based on his social media profile and other audiovisual material."),
    5: new Episode(2, 2, "White Bear", "A woman wakes up in a house with amnesia. She notices people on the street recording her on their phones, but when she speaks to them they ignore her. When a masked man opens fire at her with a shotgun, she flees and meets Jem, another woman running away from the \"hunters\"."),
    6: new Episode(2, 3, "The Waldo Moment", "Jamie Salter is a comedian controlling a vulgar computer-animated bear named Waldo on a late-night show. The character becomes popular with the British public and a pilot for a series is commissioned. Jamie reluctantly agrees to have Waldo enter an upcoming by-election to promote the pilot, having no interest in politics himself."),
    7: new Episode(3, 1, "Nosedive", "Using eye implants and mobile devices, people rate their online and in-person interactions on a five-star scale. This system cultivates insincere relationships, as a person's rating significantly affects their socioeconomic status. Lacie is a young woman currently rated at 4.2 and keen to achieve self-improvement, hoping to reach a 4.5 rating to qualify for a discount to a luxury apartment."),
    8: new Episode(3, 2, "Playtest", "Cooper leaves his home in America to travel the world, but ends up stranded in England after a banking error. He avoids calling his mother for help, as he has been unable to connect with her following his father's death due to early-onset Alzheimer's. While staying at the house of a girl he had slept with the previous night, Cooper offers to participate in a playtest of an augmented reality video game."),
    9: new Episode(3, 3, "Shut Up and Dance", "Nineteen-year-old Kenny downloads an anti-malware program to fix his infected laptop. Unbeknownst to him, the program activates his laptop camera, which records him masturbating to internet porn. Hackers threaten to e-mail a video of his act to his entire contacts list, unless he follows their instructions."),
    10: new Episode(3, 4, "San Junipero", "In 1987, shy Yorkie visits a bar in a beach resort town named San Junipero, where she meets the outgoing Kelly. The two young women are attracted to each other and they sleep together. After that, Yorkie is not able to find Kelly again, until a man suggests looking for her in a different time. Yorkie visits 1980, 1996, and finally manages to find Kelly in 2002."),
    11: new Episode(3, 5, "Men Against Fire", "Soldiers are exterminating mutated humans called \"roaches\" in a foreign country, using a neural implant called MASS, which enhances their senses and provides instant data via augmented reality. When soldier Stripe encounters several aggressive roaches, one of them uses a mysterious device that disrupts his MASS interface. "),
    12: new Episode(3, 6, "Hated in the Nation", "To counteract a drop in the United Kingdom's bee population, Granular has developed robotic bees, known as \"ADIs\". Detectives Karin Parke and Blue Coulson, together with the help of NCA agent Shaun Li, discover that hacked ADIs have caused the deaths of two people by getting inside their heads, causing unbearable pain. "),
    13: new Episode(4, 1, "USS Callister", "Robert Daly, a reclusive but gifted programmer and co-founder of a popular massive multiplayer online game, is embittered by the lack of recognition for his work. He has created a mock Star Trek-like simulation on a private server, using DNA from his co-workers to create sentient digital clones of them, serving under himself their abusive captain of the starship USS Callister. "),
    14: new Episode(4, 2, "Arkangel", "Marie briefly loses track of her three-year old daughter Sara, and decides to have her implanted with the Arkangel system, allowing Marie to use a tablet to track her, monitor her health and emotional state, and censor sights she doesn't want Sara to see, such as blood. As Sara grows up, Marie recognises that Arkangel is hampering Sara's growth."),
    15: new Episode(4, 3, "Crocodile", "Mia and her boyfriend Rob end up in a hit-and-run with a bicyclist, killing him; Rob has them dispose of the body and stay quiet on the matter. Fifteen years later, Mia is married with a son, and has a successful career. While on travel, Rob visits Mia and suggests they tell the truth about the bicyclist, but Mia, fearing this would ruin her career, kills Rob and hides his body. "),
    16: new Episode(4, 4, "Hang the DJ", "Frank and Amy are two of several that participate in the System, where they are instructed by a personal device called the Coach to meet other people and spend a pre-determined amount of time with them. Frank and Amy are matched for a short period but both find themselves attracted to each other."),
    17: new Episode(4, 5, "Metalhead", "Robotic guard-dogs have turned against humans, leaving the few human survivors to fend for themselves. While trying to retrieve supplies from a warehouse, Bella's companions are killed by the robots, but she manages to flee and evade their tracking devices."),
    18: new Episode(4, 6, "Black Museum", "Nish stops to recharge her car and enters the nearby \"Black Museum\", owned and run by Rolo Haynes. Rolo shows her various artifacts, all related to illicit technology that he had been involved with. He describes several stories connected to them. One involves Dr. Peter Dawson, a doctor who developed a device that allowed him to experience the pain of his patients to aid in diagnosis, but soon found pain giving way to addictive pleasure, and eventually killed a man to experience the sensation. "),
    19: new Episode("Special", "-", "Bandersnatch", "Young programmer Stefan Butler begins to create an adventure video game called Bandersnatch, based on a \"choose your own adventure\" book of the same name."),
}

function constructTable(show) {
    s = "<table style=\"border-collapse:collapse;\"><tr><th>Season #</th><th>Episode #</th><th>Episode Title</th><th>Episode Summary</th></tr>";
    for (var i = 1; i <= Object.keys(show).length; i++) {
        if (show[i].season == 1) {
            s += "<tr style=\"height:150px; background-color:#fada5e;\">";
            s += "<td style=\"min-width:75px\">" + show[i].season + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].ep + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].title + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].summary + "</td>";
            s += "</tr>";
        }
        else if (show[i].season == 2) {
            s += "<tr style=\"height:150px; background-color:#82f780;\">";
            s += "<td style=\"min-width:75px\">" + show[i].season + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].ep + "</td>";
            s += "<td style=\"width:75px\">" + show[i].title + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].summary + "</td>";
            s += "</tr>";
        }
        else if (show[i].season == 3) {
            s += "<tr style=\"height:150px; background-color:#a2f2e4;\">";
            s += "<td style=\"min-width:75px\">" + show[i].season + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].ep + "</td>";
            s += "<td style=\"width:75px\">" + show[i].title + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].summary + "</td>";
            s += "</tr>";
        }
        else if (show[i].season == 4) {
            s += "<tr style=\"height:150px; background-color:#cc99ff;\">";
            s += "<td style=\"min-width:75px\">" + show[i].season + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].ep + "</td>";
            s += "<td style=\"width:75px\">" + show[i].title + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].summary + "</td>";
            s += "</tr>";
        }

        else {
            s += "<tr style=\"height:150px; background-color:#ffadf2;\">";
            s += "<td style=\"min-width:75px\">" + show[i].season + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].ep + "</td>";
            s += "<td style=\"width:75px\">" + show[i].title + "</td>";
            s += "<td style=\"min-width:75px\">" + show[i].summary + "</td>";
            s += "</tr>";
        }
    }
    s += "</table>";
    return s;
}
